apiVersion: v1
name: argo-ingress
version: 0.1.0
home: https://developers.cloudflare.com/argo-tunnel/
description: Installs the cloudflare argo tunnel ingress controller
maintainers:
  - name: Nathan Franzen
    email: nate@stackpointcloud.com
