# Default values for cloudflare-argo-ingress.

# replicaCount is used only when loudflare loadbalancing is enabled
replicaCount: 1

image:
  repository: gcr.io/stackpoint-public/argot
  tag: 0.5.1
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

rbac:
  install: true
  serviceAccount: cloudflare-argo
  roleName: cloudflare-argo

## Cloudflare account details

# The secret contains the base64-encoded origin certificate for your cloudflare domain.
# Set the install flag false to configure manually in the cluster later.
# See https://developers.cloudflare.com/argo-tunnel/quickstart/quickstart/ for information on
# obtaining the origin certificate
secret:
  install: false
  domain: example.co
  certificate_b64: LS0tLS1CRUdJT...insert base64-encoded certificate here

loadbalancing:
  enabled: false

