
# https://kubernetes.io/blog/2018/01/introducing-client-go-version-6

# required = [
#   "k8s.io/code-generator/cmd/client-gen",
#   "k8s.io/code-generator/cmd/conversion-gen",
#   "k8s.io/code-generator/cmd/deepcopy-gen",
#   "k8s.io/code-generator/cmd/defaulter-gen",
#   "k8s.io/code-generator/cmd/informer-gen",
#   "k8s.io/code-generator/cmd/lister-gen",
# ]

# [[constraint]]
#   branch = "kubernetes-1.9.0"
#   name = "k8s.io/code-generator"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "6.0.0"

[[constraint]]
name = "github.com/cloudflare/cloudflared"
source = "https://github.com/StackPointCloud/cloudflared.git"
revision = "5e7151649a6d8f6f07a3b6137b00054feeea7a49"