{{ if .Values.rbac.install }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rbac.roleName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.rbac.roleName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.serviceAccount }}
{{ end }}
